spring.application.name=forum-service

spring.data.mongodb.uri=\
  mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.ypoimvw.mongodb.net/${MONGODB_BASE}?retryWrites=true&w=majority&appName=Cluster0

security.password.expiry-days=60

